version: "3"

services:
  mongodb:
    image: "mongo:latest"
    expose:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: "members"

  fastapi-server:
    build:
      context: ./server
    expose:
      - "8000"
    depends_on:
      - mongodb

  streamlit-client:
    build:
      context: ./client
    ports:
      - "8501:8501"
    depends_on:
      - fastapi-server
